import {useEffect,useMemo,useState} from 'react';
import {Plus,HeartPulse} from 'lucide-react';
import {Button,Card,Empty,Field,Modal,TextInput,ghost,input} from '../../components/common/ui';
import {employeeService} from '../employees/employeeService';
import type {Employee} from '../../types/domain';
import {hmoService} from './hmoService';
import type {HmoDependent,HmoEnrollment,HmoPlan,HmoProvider,HmoUtilization} from './hmoTypes';

const today=()=>new Date().toISOString().slice(0,10);
const money=(n:number|null|undefined)=>n==null?'—':new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:2}).format(n);

export default function HmoBenefits(){
 const [tab,setTab]=useState<'plan'|'enrollment'|'dependents'|'utilization'|'history'>('plan');
 const [providers,setProviders]=useState<HmoProvider[]>([]),[plans,setPlans]=useState<HmoPlan[]>([]),[enrollments,setEnrollments]=useState<HmoEnrollment[]>([]),[dependents,setDependents]=useState<HmoDependent[]>([]),[utilizations,setUtilizations]=useState<HmoUtilization[]>([]),[employees,setEmployees]=useState<Employee[]>([]);
 const [loading,setLoading]=useState(true),[planModal,setPlanModal]=useState(false),[enrollModal,setEnrollModal]=useState(false),[dependentModal,setDependentModal]=useState(false),[utilModal,setUtilModal]=useState(false);
 const load=async()=>{setLoading(true);try{const [p,pl,e,d,u,emp]=await Promise.all([hmoService.providers(),hmoService.plans(),hmoService.enrollments(),hmoService.dependents(),hmoService.utilizations(),employeeService.getAll()]);setProviders(p);setPlans(pl);setEnrollments(e);setDependents(d);setUtilizations(u);setEmployees(emp)}catch(error){console.error(error)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const activePlan=plans.find(p=>p.status==='Active')??plans.find(p=>p.status==='Draft');
 const activeProvider=providers.find(p=>p.status==='Active');
 const employeeMap=useMemo(()=>new Map(employees.map(e=>[e.id,e])),[employees]);
 const activeEnrollments=enrollments.filter(e=>['Pending','Submitted','Active'].includes(e.status));
 const totalUsed=utilizations.filter(u=>u.status==='Recorded').reduce((s,u)=>s+Number(u.amountUsed||0),0);
 const tabs=[['plan','HMO Plan'],['enrollment','Employee Enrollment'],['dependents','Dependents'],['utilization','HMO Utilization'],['history','HMO History']] as const;
 return <div>
  <div className="flex items-start justify-between gap-4"><div><h1 className="m-0 text-[22px] font-semibold">HMO & Benefits</h1><p className="mt-1 text-[12.5px] text-[#6b7794]">Manage the company HMO plan, employee enrollment, dependents, utilization, and history.</p></div><div className="flex items-center gap-2 rounded-xl border border-[#e3e7ef] px-3 py-2 text-[12px]"><HeartPulse size={16}/><span>{activeProvider?.name??'No active provider'}</span></div></div>
  <div className="mt-5 flex flex-wrap gap-1 rounded-xl border border-[#e3e7ef] bg-white p-1">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={tab===key?'rounded-lg bg-[#eef4f7] px-3 py-2 text-[12px] font-semibold text-[#2f6b86]':'rounded-lg px-3 py-2 text-[12px] text-[#6b7794]'}>{label}</button>)}</div>
  {loading?<Card className="mt-4"><Empty>Loading HMO records…</Empty></Card>:<>
   {tab==='plan'&&<PlanSection provider={activeProvider} plan={activePlan} onAdd={()=>setPlanModal(true)}/>}
   {tab==='enrollment'&&<EnrollmentSection employees={employees} enrollments={enrollments} plans={plans} employeeMap={employeeMap} onAdd={()=>setEnrollModal(true)}/>}
   {tab==='dependents'&&<DependentSection dependents={dependents} enrollments={enrollments} employeeMap={employeeMap} onAdd={()=>setDependentModal(true)}/>}
   {tab==='utilization'&&<UtilizationSection utilizations={utilizations} enrollments={enrollments} employeeMap={employeeMap} totalUsed={totalUsed} onAdd={()=>setUtilModal(true)}/>}
   {tab==='history'&&<HistorySection plans={plans} enrollments={enrollments} dependents={dependents}/>}
  </>}
  {planModal&&<PlanModal provider={activeProvider} onClose={()=>setPlanModal(false)} onSaved={()=>{setPlanModal(false);load()}}/>}
  {enrollModal&&<EnrollmentModal employees={employees} plan={activePlan} onClose={()=>setEnrollModal(false)} onSaved={()=>{setEnrollModal(false);load()}}/>}
  {dependentModal&&<DependentModal enrollments={activeEnrollments} employeeMap={employeeMap} onClose={()=>setDependentModal(false)} onSaved={()=>{setDependentModal(false);load()}}/>}
  {utilModal&&<UtilizationModal enrollments={enrollments.filter(e=>e.status==='Active')} dependents={dependents} employeeMap={employeeMap} onClose={()=>setUtilModal(false)} onSaved={()=>{setUtilModal(false);load()}}/>}
 </div>
}

function PlanSection({provider,plan,onAdd}:{provider?:HmoProvider;plan?:HmoPlan;onAdd:()=>void}){return <><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Provider',provider?.name??'—'],['Plan',plan?.name??'Not configured'],['Coverage',plan?plan.coverageStart+' – '+plan.coverageEnd:'—'],['Annual Limit',money(plan?.annualBenefitLimit)]].map(([l,v])=><Card key={l}><div className="text-[12px] text-[#6b7794]">{l}</div><div className="mt-1 font-semibold">{v}</div></Card>)}</div><div className="mt-4 flex justify-end">{!plan&&<Button onClick={onAdd}><Plus size={15}/>Create HMO Plan</Button>}</div>{!plan?<Card className="mt-4"><Empty>No HMO plan configured yet.</Empty></Card>:<Card className="mt-4"><div className="flex items-start justify-between"><div><h2 className="m-0 text-[16px] font-semibold">{plan.name}</h2><p className="mt-1 text-[12px] text-[#6b7794]">{plan.status} · Principal employee is {plan.employeeCompanyShare}% company-paid.</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700">{plan.status}</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Inpatient',plan.inpatient],['Outpatient',plan.outpatient],['Emergency',plan.emergency],['Preventive Care',plan.preventiveCare]].map(([l,v])=><div key={l} className="rounded-xl border border-[#e3e7ef] p-3"><div className="text-[11px] text-[#6b7794]">{l}</div><div className="mt-1 font-semibold">{v?'Covered':'Not included'}</div></div>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><div className="text-[11px] uppercase tracking-wide text-[#6b7794]">Principal employee</div><div className="mt-1 font-semibold">{plan.employeeCompanyShare}% company / {plan.employeeMemberShare}% employee</div></div><div><div className="text-[11px] uppercase tracking-wide text-[#6b7794]">Dependents</div><div className="mt-1 font-semibold">{plan.dependentCompanyShare}% company / {plan.dependentMemberShare}% employee</div></div></div></Card>}</>}

function EnrollmentSection({employees,enrollments,plans,employeeMap,onAdd}:{employees:Employee[];enrollments:HmoEnrollment[];plans:HmoPlan[];employeeMap:Map<string,Employee>;onAdd:()=>void}){return <><div className="mt-4 flex justify-end"><Button disabled={!employees.length||!plans.some(p=>p.status==='Active'||p.status==='Draft')} onClick={onAdd}><Plus size={15}/>Enroll Employee</Button></div><Card className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-[13px]"><thead><tr className="border-b border-[#e3e7ef] text-[11px] uppercase tracking-wide text-[#6b7794]">{['Employee','Plan','Eligibility','Effective','Expiration','Status'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{enrollments.length===0?<tr><td colSpan={6}><Empty>No HMO enrollments yet.</Empty></td></tr>:enrollments.map(e=><tr key={e.id} className="border-b border-[#eef1f6]"><td className="px-4 py-3 font-semibold">{employeeMap.get(e.employeeId)?.name??e.employeeId}</td><td className="px-4 py-3">{plans.find(p=>p.id===e.planId)?.name??'—'}</td><td className="px-4 py-3">{e.eligibilityDate??'—'}</td><td className="px-4 py-3">{e.effectiveDate}</td><td className="px-4 py-3">{e.expirationDate??'—'}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold">{e.status}</span></td></tr>)}</tbody></table></Card></>}

function DependentSection({dependents,enrollments,employeeMap,onAdd}:{dependents:HmoDependent[];enrollments:HmoEnrollment[];employeeMap:Map<string,Employee>;onAdd:()=>void}){return <><div className="mt-4 flex justify-end"><Button disabled={!enrollments.some(e=>e.status==='Active')} onClick={onAdd}><Plus size={15}/>Add Dependent</Button></div><Card className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-[13px]"><thead><tr className="border-b border-[#e3e7ef] text-[11px] uppercase tracking-wide text-[#6b7794]">{['Employee','Dependent','Relationship','Eligibility','Effective','Status'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{dependents.length===0?<tr><td colSpan={6}><Empty>No dependents enrolled.</Empty></td></tr>:dependents.map(d=>{const e=enrollments.find(x=>x.id===d.enrollmentId);return <tr key={d.id} className="border-b border-[#eef1f6]"><td className="px-4 py-3">{e?employeeMap.get(e.employeeId)?.name??e.employeeId:'—'}</td><td className="px-4 py-3 font-semibold">{d.name}</td><td className="px-4 py-3">{d.relationship}</td><td className="px-4 py-3">{d.eligibilityStatus}</td><td className="px-4 py-3">{d.effectiveDate??'—'}</td><td className="px-4 py-3">{d.status}</td></tr>})}</tbody></table></Card></>}

function UtilizationSection({utilizations,enrollments,employeeMap,totalUsed,onAdd}:{utilizations:HmoUtilization[];enrollments:HmoEnrollment[];employeeMap:Map<string,Employee>;totalUsed:number;onAdd:()=>void}){return <><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-3"><Card><div className="text-[12px] text-[#6b7794]">Recorded Services</div><div className="mt-1 text-[20px] font-semibold">{utilizations.filter(u=>u.status==='Recorded').length}</div></Card><Card><div className="text-[12px] text-[#6b7794]">Total Benefit Used</div><div className="mt-1 text-[20px] font-semibold">{money(totalUsed)}</div></Card><Card><div className="text-[12px] text-[#6b7794]">Active Enrollments</div><div className="mt-1 text-[20px] font-semibold">{enrollments.filter(e=>e.status==='Active').length}</div></Card></div><div className="mt-4 flex justify-end"><Button disabled={!enrollments.some(e=>e.status==='Active')} onClick={onAdd}><Plus size={15}/>Record Utilization</Button></div><Card className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-[13px]"><thead><tr className="border-b border-[#e3e7ef] text-[11px] uppercase tracking-wide text-[#6b7794]">{['Member','Service','Date','Amount Used','Status','Remarks'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{utilizations.length===0?<tr><td colSpan={6}><Empty>No utilization records yet.</Empty></td></tr>:utilizations.map(u=>{const e=enrollments.find(x=>x.id===u.enrollmentId);return <tr key={u.id} className="border-b border-[#eef1f6]"><td className="px-4 py-3">{e?employeeMap.get(e.employeeId)?.name??e.employeeId:'—'}</td><td className="px-4 py-3">{u.serviceType}</td><td className="px-4 py-3">{u.serviceDate}</td><td className="px-4 py-3 font-semibold">{money(u.amountUsed)}</td><td className="px-4 py-3">{u.status}</td><td className="px-4 py-3">{u.remarks||'—'}</td></tr>})}</tbody></table></Card></>}

function HistorySection({plans,enrollments,dependents}:{plans:HmoPlan[];enrollments:HmoEnrollment[];dependents:HmoDependent[]}){const historyPlans=plans.filter(p=>p.status!=='Active'),historyEnrollments=enrollments.filter(e=>!['Pending','Submitted','Active'].includes(e.status));return <div className="mt-4 grid gap-4 lg:grid-cols-2"><Card><h2 className="m-0 text-[16px] font-semibold">Plan History</h2>{historyPlans.length===0?<Empty>No expired or archived plans.</Empty>:<div className="mt-3 space-y-2">{historyPlans.map(p=><div key={p.id} className="rounded-xl border border-[#e3e7ef] p-3"><b>{p.name}</b><div className="text-[12px] text-[#6b7794]">{p.coverageStart} – {p.coverageEnd} · {p.status}</div></div>)}</div>}</Card><Card><h2 className="m-0 text-[16px] font-semibold">Enrollment History</h2>{historyEnrollments.length===0?<Empty>No completed enrollment history.</Empty>:<div className="mt-3 space-y-2">{historyEnrollments.map(e=><div key={e.id} className="rounded-xl border border-[#e3e7ef] p-3"><b>{e.status}</b><div className="text-[12px] text-[#6b7794]">{e.effectiveDate} – {e.expirationDate??'—'}</div></div>)}</div>}<div className="mt-5 text-[12px] text-[#6b7794]">{dependents.length} dependent record(s) retained.</div></Card></div>}

function PlanModal({provider,onClose,onSaved}:{provider?:HmoProvider;onClose:()=>void;onSaved:()=>void}){const[f,setF]=useState({name:'',start:today(),end:'',limit:'100000',employeePremium:'1200',dependentPremium:'800',inpatient:true,outpatient:true,emergency:true,preventive:true,dental:false});const save=async()=>{if(!f.name||!f.end)return;let p=provider;if(!p){p=await hmoService.createProvider({name:'Maxicare',status:'Active'})}await hmoService.createPlan({providerId:p.id,name:f.name,coverageStart:f.start,coverageEnd:f.end,annualBenefitLimit:Number(f.limit)||null,inpatient:f.inpatient,outpatient:f.outpatient,emergency:f.emergency,preventiveCare:f.preventive,dental:f.dental,employeeCompanyShare:100,employeeMemberShare:0,dependentCompanyShare:0,dependentMemberShare:100,employeeMonthlyPremium:Number(f.employeePremium)||null,dependentMonthlyPremium:Number(f.dependentPremium)||null,collectEmployeeShareViaPayroll:true,status:'Active'});onSaved()};return <Modal title="Create HMO Plan" onClose={onClose}><div className="grid gap-4"><Field label="HMO Provider"><TextInput value={provider?.name??'Maxicare'} readOnly/></Field><Field label="Plan Name"><TextInput value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Corporate Gold"/></Field><div className="grid grid-cols-2 gap-3"><Field label="Coverage Start"><TextInput type="date" value={f.start} onChange={e=>setF({...f,start:e.target.value})}/></Field><Field label="Coverage End"><TextInput type="date" value={f.end} onChange={e=>setF({...f,end:e.target.value})}/></Field></div><Field label="Annual Benefit Limit"><TextInput type="number" value={f.limit} onChange={e=>setF({...f,limit:e.target.value})}/></Field><div className="grid grid-cols-2 gap-2 text-[12px]">{[['inpatient','Inpatient'],['outpatient','Outpatient'],['emergency','Emergency'],['preventive','Preventive Care'],['dental','Dental']].map(([k,l])=><label key={k} className="flex items-center gap-2"><input type="checkbox" checked={Boolean(f[k as keyof typeof f])} onChange={e=>setF({...f,[k]:e.target.checked})}/>{l}</label>)}</div><div className="rounded-xl border border-[#e3e7ef] p-3 text-[12px]"><b>Contribution policy</b><div className="mt-2">Principal employee: <b>100% company / 0% employee</b></div><div className="mt-1">Dependents: <b>0% company / 100% employee</b></div><div className="mt-1 text-[#6b7794]">Employee-paid contributions may be collected through Payroll.</div></div></div><div className="mt-6 flex justify-end gap-2"><button className={ghost} onClick={onClose}>Cancel</button><Button disabled={!f.name||!f.end} onClick={save}>Activate Plan</Button></div></Modal>}

function EnrollmentModal({employees,plan,onClose,onSaved}:{employees:Employee[];plan?:HmoPlan;onClose:()=>void;onSaved:()=>void}){const[f,setF]=useState({employeeId:'',eligibility:today(),effective:today(),expiration:plan?.coverageEnd??''});const save=async()=>{if(!f.employeeId||!plan)return;await hmoService.createEnrollment({planId:plan.id,employeeId:f.employeeId,eligibilityDate:f.eligibility,effectiveDate:f.effective,expirationDate:f.expiration||null,status:'Pending'});onSaved()};return <Modal title="Enroll Employee" onClose={onClose}><div className="grid gap-4"><Field label="Employee"><select className={input} value={f.employeeId} onChange={e=>setF({...f,employeeId:e.target.value})}><option value="">Select eligible employee</option>{employees.filter(e=>e.status==='Active').map(e=><option key={e.id} value={e.id}>{e.name} ({e.employeeNo})</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Eligibility Date"><TextInput type="date" value={f.eligibility} onChange={e=>setF({...f,eligibility:e.target.value})}/></Field><Field label="Effective Date"><TextInput type="date" value={f.effective} onChange={e=>setF({...f,effective:e.target.value})}/></Field></div><Field label="Expiration Date"><TextInput type="date" value={f.expiration} onChange={e=>setF({...f,expiration:e.target.value})}/></Field><p className="text-[12px] text-[#6b7794]">Enrollment starts as Pending. HMO confirmation is required before it becomes Active.</p></div><div className="mt-6 flex justify-end gap-2"><button className={ghost} onClick={onClose}>Cancel</button><Button disabled={!f.employeeId||!plan} onClick={save}>Submit Enrollment</Button></div></Modal>}

function DependentModal({enrollments,employeeMap,onClose,onSaved}:{enrollments:HmoEnrollment[];employeeMap:Map<string,Employee>;onClose:()=>void;onSaved:()=>void}){const[f,setF]=useState({enrollmentId:'',name:'',relationship:'Spouse',dob:''});const save=async()=>{if(!f.enrollmentId||!f.name)return;await hmoService.createDependent({enrollmentId:f.enrollmentId,name:f.name,relationship:f.relationship,dateOfBirth:f.dob||null,eligibilityStatus:'Pending',effectiveDate:today(),status:'Pending'});onSaved()};return <Modal title="Add Dependent" onClose={onClose}><div className="grid gap-4"><Field label="Employee"><select className={input} value={f.enrollmentId} onChange={e=>setF({...f,enrollmentId:e.target.value})}><option value="">Select employee</option>{enrollments.map(e=><option key={e.id} value={e.id}>{employeeMap.get(e.employeeId)?.name??e.employeeId}</option>)}</select></Field><Field label="Dependent Name"><TextInput value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Relationship"><select className={input} value={f.relationship} onChange={e=>setF({...f,relationship:e.target.value})}><option>Spouse</option><option>Child</option><option>Parent</option><option>Other Eligible Dependent</option></select></Field><Field label="Date of Birth"><TextInput type="date" value={f.dob} onChange={e=>setF({...f,dob:e.target.value})}/></Field><p className="text-[12px] text-[#6b7794]">Dependent coverage follows the active plan contribution policy and requires eligibility/HMO confirmation.</p></div><div className="mt-6 flex justify-end gap-2"><button className={ghost} onClick={onClose}>Cancel</button><Button disabled={!f.enrollmentId||!f.name} onClick={save}>Submit Dependent</Button></div></Modal>}

function UtilizationModal({enrollments,dependents,employeeMap,onClose,onSaved}:{enrollments:HmoEnrollment[];dependents:HmoDependent[];employeeMap:Map<string,Employee>;onClose:()=>void;onSaved:()=>void}){const[f,setF]=useState({enrollmentId:'',dependentId:'',date:today(),service:'Consultation',amount:'',remarks:''});const save=async()=>{if(!f.enrollmentId||!f.service||Number(f.amount)<0)return;await hmoService.createUtilization({enrollmentId:f.enrollmentId,dependentId:f.dependentId||null,serviceDate:f.date,serviceType:f.service,amountUsed:Number(f.amount)||0,status:'Recorded',remarks:f.remarks||null});onSaved()};return <Modal title="Record HMO Utilization" onClose={onClose}><div className="grid gap-4"><Field label="Member"><select className={input} value={f.enrollmentId} onChange={e=>setF({...f,enrollmentId:e.target.value,dependentId:''})}><option value="">Select employee</option>{enrollments.map(e=><option key={e.id} value={e.id}>{employeeMap.get(e.employeeId)?.name??e.employeeId}</option>)}</select></Field><Field label="Dependent (optional)"><select className={input} value={f.dependentId} onChange={e=>setF({...f,dependentId:e.target.value})}><option value="">Principal employee</option>{dependents.filter(d=>d.enrollmentId===f.enrollmentId).map(d=><option key={d.id} value={d.id}>{d.name} ({d.relationship})</option>)}</select></Field><Field label="Service Type"><select className={input} value={f.service} onChange={e=>setF({...f,service:e.target.value})}><option>Consultation</option><option>Laboratory</option><option>Hospitalization</option><option>Emergency</option><option>Preventive Care</option><option>Dental</option><option>Other</option></select></Field><div className="grid grid-cols-2 gap-3"><Field label="Service Date"><TextInput type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Benefit Used"><TextInput type="number" min="0" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field></div><Field label="Remarks"><TextInput value={f.remarks} onChange={e=>setF({...f,remarks:e.target.value})}/></Field></div><div className="mt-6 flex justify-end gap-2"><button className={ghost} onClick={onClose}>Cancel</button><Button disabled={!f.enrollmentId||Number(f.amount)<0} onClick={save}>Record Utilization</Button></div></Modal>}
