export type HmoStatus='Draft'|'Active'|'Expiring'|'Expired'|'Archived';
export type HmoEnrollmentStatus='Pending'|'Submitted'|'Active'|'Rejected'|'Terminated'|'Expired';
export type HmoApprovalStatus='Pending'|'Approved'|'Rejected';
export type MaxicareStatus='Not Submitted'|'Pending'|'Active'|'Rejected';
export interface HmoProvider{id:string;name:string;contactPerson?:string|null;contactNumber?:string|null;status:'Active'|'Inactive'|'Archived';}
export interface HmoPlan{id:string;providerId:string;name:string;coverageStart:string;coverageEnd:string;annualBenefitLimit:number|null;inpatient:boolean;outpatient:boolean;emergency:boolean;preventiveCare:boolean;dental:boolean;employeeCompanyShare:number;employeeMemberShare:number;dependentCompanyShare:number;dependentMemberShare:number;employeeMonthlyPremium:number|null;dependentMonthlyPremium:number|null;collectEmployeeShareViaPayroll:boolean;status:HmoStatus;}
export interface HmoEnrollment{id:string;planId:string;employeeId:string;eligibilityDate:string|null;effectiveDate:string;expirationDate:string|null;status:HmoEnrollmentStatus;approvalStatus:HmoApprovalStatus;approvedBy?:string|null;approvedAt?:string|null;rejectionReason?:string|null;maxicareStatus:MaxicareStatus;maxicareReference?:string|null;maxicareActivatedAt?:string|null;activatedAt?:string|null;terminatedAt?:string|null;}
export interface HmoDependent{id:string;enrollmentId:string;name:string;relationship:string;dateOfBirth:string|null;eligibilityStatus:'Pending'|'Eligible'|'Not Eligible';effectiveDate:string|null;expirationDate:string|null;status:HmoEnrollmentStatus;approvalStatus:HmoApprovalStatus;approvedBy?:string|null;approvedAt?:string|null;rejectionReason?:string|null;companySponsored:boolean;employeeShare:number;companyShare:number;}
export interface HmoUtilization{id:string;enrollmentId:string;dependentId:string|null;serviceDate:string;serviceType:string;amountUsed:number;status:'Recorded'|'Voided';remarks:string|null;}
export interface HmoHistoryRow{id:string;entityType:string;entityId:string;action:string;actorId:string|null;previousValues:Record<string,unknown>;newValues:Record<string,unknown>;createdAt:string;}
export interface HmoPayrollDeduction{id:string;employeeId:string;enrollmentId:string;periodStart:string;periodEnd:string;amount:number;verificationStatus:'Pending'|'Verified'|'Rejected';verifiedBy:string|null;verifiedAt:string|null;createdAt:string;}
