import {useState} from 'react';
import {Card,Empty,Modal,ghost} from '../../components/common/ui';
import type {Employee,PayrollInput,PayrollResult} from '../../types/domain';
import {numberValue,peso} from '../../utils/storage';
type Computed={r:PayrollInput;c:PayrollResult};
export function PayrollRuns(){
 const metrics=[{label:'Total Runs',hint:'Persisted run count unavailable'},{label:'Completed',hint:'Completion metrics unavailable'},{label:'Processing',hint:'Processing metrics unavailable'},{label:'For Approval',hint:'Approval metrics unavailable'}];
 return <section aria-labelledby="payroll-runs-title" className="min-w-0 space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 id="payroll-runs-title" className="m-0 text-[26px] font-bold tracking-tight text-slate-900">Payroll Runs</h2><p className="mb-0 mt-2 text-[13px] leading-relaxed text-slate-500">Create and manage payroll runs for employee compensation.</p></div><span className="inline-flex rounded-lg border border-slate-200 bg-white px-3 py-2 text-[11px] font-semibold text-slate-500">Run integration unavailable</span></div>
  <div className="rounded-xl border border-blue-100 bg-blue-50/60 px-4 py-3 text-[12px] leading-relaxed text-blue-800">Persisted payroll run data and run actions are not available through the current frontend integration. Local payroll calculations are not payroll runs.</div>
  <div aria-label="Payroll Runs summary" className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,hint})=><Card key={label}><div className="flex items-center justify-between gap-3"><div className="text-[12px] font-medium text-slate-500">{label}</div><span aria-hidden="true" className="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-blue-500">—</span></div><div className="mt-3 text-[20px] font-semibold tracking-tight text-[#17345b]">Unavailable</div><div className="mt-2 text-[11px] text-slate-400">{hint}</div></Card>)}</div>
  <Card className="min-w-0"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h3 className="m-0 text-[16px] font-semibold text-slate-800">Payroll Runs Records</h3><p className="mb-0 mt-1 text-[12px] text-slate-500">Existing run fields · no sample records or financial amounts</p></div><span className="rounded-lg bg-slate-50 px-3 py-1.5 text-[11px] text-slate-500">Records unavailable</span></div><div role="region" aria-label="Payroll Runs records table" tabIndex={0} className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[1050px] text-left text-[13px]"><thead><tr className="border-b bg-[#f3f5f9] text-[11px] uppercase tracking-wide text-slate-500">{['Run ID','Payroll Period','Pay Date','Employees','Gross Pay','Deductions','Net Pay','Status','Action'].map(label=><th key={label} scope="col" className="px-4 py-3">{label}</th>)}</tr></thead><tbody><tr><td colSpan={9}><Empty><div className="font-semibold text-slate-700">Payroll run records are unavailable</div><div className="mt-2 text-[12px] leading-relaxed">No persisted run data is connected to this view. Counts, statuses and amounts cannot be determined.</div></Empty></td></tr></tbody></table></div><div className="mt-4 border-t border-slate-100 pt-3 text-[11px] leading-relaxed text-slate-500">Intended workflow: Draft → For Review → Approved → Processed.<br/>Workflow transitions, date/search/status filters, export, pagination and Create Run are not supported by this view.</div></Card>
 </section>;
}
export function PayrollReport({kind,computed,employees}:{kind:'payslip'|'summary';computed:Computed[];employees:Employee[]}){
 const[view,setView]=useState<Computed|null>(null);
 const sum=(key:keyof PayrollResult)=>computed.reduce((total,item)=>total+item.c[key],0);
 const employee=(r:PayrollInput)=>employees.find(item=>item.id===r.empId||item.employeeNo===r.empId);
 const shares=(c:PayrollResult)=>c.sss+c.phil+c.pagibig;
 const allowance=(r:PayrollInput)=>numberValue(r.transportation)+numberValue(r.riceSubsidy);
 const title=kind==='payslip'?'Payslip':'Payroll Summary';
 const cards:Array<[string,string|number]>=[['Employees',new Set(computed.map(item=>item.r.empId)).size],['Gross Payroll',peso(sum('gross'))],['Deductions',peso(sum('deductions'))],['Net Payroll',peso(sum('net'))],['Overtime',peso(sum('overtime'))],['Government Deductions (employee)',peso(sum('sss')+sum('phil')+sum('pagibig'))]];
 return <div><h1 className="m-0 text-[22px] font-semibold">{title}</h1><p className="mt-1 text-[12.5px] text-[#6b7794]">Existing local payroll calculations. Payroll period, approval status, employer contributions and persisted payslip issuance are unavailable; amounts do not represent remittance records.</p>
 {kind==='summary'?<><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label,value])=><Card key={label}><div className="text-[12px] text-[#6b7794]">{label}</div><div className="mt-1 text-[22px] font-semibold">{value}</div></Card>)}</div><Card className="mt-4"><h2 className="text-[16px] font-semibold">Government Contributions</h2><dl className="grid gap-3 sm:grid-cols-3">{[['SSS',sum('sss')],['PhilHealth',sum('phil')],['Pag-IBIG',sum('pagibig')]].map(([label,value])=><div key={label}><dt className="text-[12px] text-[#6b7794]">{label} employee deduction</dt><dd className="m-0 font-semibold">{peso(value)}</dd></div>)}</dl><p className="text-[12px] text-[#6b7794]">Employer shares and contribution payment history: unavailable.</p></Card><button className={`${ghost} mt-4`} onClick={()=>window.print()}>Print Summary</button></>:<Card className="mt-5 overflow-x-auto"><table className="w-full min-w-[1600px] text-left text-[13px]"><thead><tr className="border-b text-[11px] uppercase text-[#6b7794]">{['Employee','Employee #','Payroll Period','Basic Pay','Allowances','Overtime','Gross Pay','Government Deductions','Other Deductions','Net Pay','Status','Action'].map(label=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{!computed.length?<tr><td colSpan={12}><Empty>No existing payroll calculations available.</Empty></td></tr>:computed.map(item=>{const{r,c}=item;return <tr key={r.id} className="border-b"><td className="px-3 py-3">{employee(r)?.name||r.name}</td><td className="px-3 py-3">{employee(r)?.employeeNo||'Unavailable'}</td><td className="px-3 py-3">Unavailable</td><td className="px-3 py-3">{peso(c.basic)}</td><td className="px-3 py-3">{peso(allowance(r))}</td><td className="px-3 py-3">{peso(c.overtime)}</td><td className="px-3 py-3">{peso(c.gross)}</td><td className="px-3 py-3">{peso(shares(c))}</td><td className="px-3 py-3">{peso(c.deductions-shares(c))}</td><td className="px-3 py-3">{peso(c.net)}</td><td className="px-3 py-3">Unavailable</td><td className="px-3 py-3"><button className={ghost} onClick={()=>setView(item)}>View / Print</button></td></tr>})}</tbody></table></Card>}
 {view&&<Modal title="Payroll calculation preview — not an issued payslip" wide onClose={()=>setView(null)}><dl className="grid gap-3 text-[13px]">{[['Employee',employee(view.r)?.name||view.r.name],['Employee #',employee(view.r)?.employeeNo||'Unavailable'],['Payroll Period','Unavailable'],['Basic Pay',peso(view.c.basic)],['Allowances',peso(allowance(view.r))],['Overtime',peso(view.c.overtime)],['Other Earnings / Leave / Holiday',peso(view.c.gross-view.c.basic-view.c.overtime-allowance(view.r))],['Gross Pay',peso(view.c.gross)],['Government Deductions',peso(shares(view.c))],['Other Deductions',peso(view.c.deductions-shares(view.c))],['Net Pay',peso(view.c.net)],['Approval / Issuance Status','Unavailable']].map(([label,value])=><div key={label} className="flex justify-between gap-3"><dt>{label}</dt><dd className="m-0 font-semibold">{value}</dd></div>)}</dl><button className={`${ghost} mt-5`} onClick={()=>window.print()}>Print Preview</button></Modal>}
 </div>;
}
