import {useState} from 'react';
import {Card,Empty,Modal,ghost} from '../../components/common/ui';
import type {Employee,PayrollInput,PayrollResult} from '../../types/domain';
import {numberValue,peso} from '../../utils/storage';
type Computed={r:PayrollInput;c:PayrollResult};
export function PayrollRuns(){return <div><h2 className="mt-4 text-[16px] font-semibold">Payroll Runs</h2><p className="text-[12px] text-[#6b7794]">Intended workflow: Draft → For Review → Approved → Processed. Run records and transitions are unavailable through the current frontend integration.</p><Card className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-[13px]"><thead><tr className="border-b text-[11px] uppercase text-[#6b7794]">{['Run ID','Payroll Period','Pay Date','Employees','Gross Pay','Deductions','Net Pay','Status','Action'].map(label=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody><tr><td colSpan={9}><Empty>Payroll run data is unavailable. Local payroll calculations are not payroll runs.</Empty></td></tr></tbody></table></Card></div>}
export function PayrollReport({kind,computed,employees}:{kind:'payslip'|'summary';computed:Computed[];employees:Employee[]}){
 const[view,setView]=useState<Computed|null>(null);
 const sum=(key:keyof PayrollResult)=>computed.reduce((total,item)=>total+item.c[key],0);
 const employee=(r:PayrollInput)=>employees.find(item=>item.id===r.empId||item.employeeNo===r.empId);
 const shares=(c:PayrollResult)=>c.sss+c.phil+c.pagibig;
 const allowance=(r:PayrollInput)=>numberValue(r.transportation)+numberValue(r.riceSubsidy);
 const title=kind==='payslip'?'Payslip':'Payroll Summary';
 const cards:Array<[string,string|number]>=[['Employees',new Set(computed.map(item=>item.r.empId)).size],['Gross Payroll',peso(sum('gross'))],['Deductions',peso(sum('deductions'))],['Net Payroll',peso(sum('net'))],['Overtime',peso(sum('overtime'))],['Government Deductions (employee)',peso(sum('sss')+sum('phil')+sum('pagibig'))]];
 return <div><h1 className="m-0 text-[22px] font-semibold">{title}</h1><p className="mt-1 text-[12.5px] text-[#6b7794]">Existing local payroll calculations. Payroll period, approval status, employer contributions and persisted payslip issuance are unavailable; amounts do not represent remittance records.</p>
 {kind==='summary'?<><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label,value])=><Card key={label}><div className="text-[12px] text-[#6b7794]">{label}</div><div className="mt-1 text-[22px] font-semibold">{value}</div></Card>)}</div><Card className="mt-4"><h2 className="text-[16px] font-semibold">Government Contributions</h2><dl className="grid gap-3 sm:grid-cols-3">{[['SSS',sum('sss')],['PhilHealth',sum('phil')],['Pag-IBIG',sum('pagibig')]].map(([label,value])=><div key={label}><dt className="text-[12px] text-[#6b7794]">{label} employee deduction</dt><dd className="m-0 font-semibold">{peso(value)}</dd></div>)}</dl><p className="text-[12px] text-[#6b7794]">Employer shares and contribution payment history: unavailable.</p></Card><button className={`${ghost} mt-4`} onClick={()=>window.print()}>Print Summary</button></>:<Card className="mt-5 overflow-x-auto"><table className="w-full min-w-[1600px] text-left text-[13px]"><thead><tr className="border-b text-[11px] uppercase text-[#6b7794]">{['Employee','Employee #','Payroll Period','Basic Pay','Allowances','Overtime','Gross Pay','Government Deductions','Other Deductions','Net Pay','Status','Action'].map(label=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{!computed.length?<tr><td colSpan={12}><Empty>No existing payroll calculations available.</Empty></td></tr>:computed.map(item=>{const{r,c}=item;return <tr key={r.id} className="border-b"><td className="px-3 py-3">{employee(r)?.name||r.name}</td><td className="px-3 py-3">{employee(r)?.employeeNo||'Unavailable'}</td><td className="px-3 py-3">Unavailable</td><td className="px-3 py-3">{peso(c.basic)}</td><td className="px-3 py-3">{peso(allowance(r))}</td><td className="px-3 py-3">{peso(c.overtime)}</td><td className="px-3 py-3">{peso(c.gross)}</td><td className="px-3 py-3">{peso(shares(c))}</td><td className="px-3 py-3">{peso(c.deductions-shares(c))}</td><td className="px-3 py-3">{peso(c.net)}</td><td className="px-3 py-3">Unavailable</td><td className="px-3 py-3"><button className={ghost} onClick={()=>setView(item)}>View / Print</button></td></tr>})}</tbody></table></Card>}
 {view&&<Modal title="Payroll calculation preview — not an issued payslip" wide onClose={()=>setView(null)}><dl className="grid gap-3 text-[13px]">{[['Employee',employee(view.r)?.name||view.r.name],['Employee #',employee(view.r)?.employeeNo||'Unavailable'],['Payroll Period','Unavailable'],['Basic Pay',peso(view.c.basic)],['Allowances',peso(allowance(view.r))],['Overtime',peso(view.c.overtime)],['Other Earnings / Leave / Holiday',peso(view.c.gross-view.c.basic-view.c.overtime-allowance(view.r))],['Gross Pay',peso(view.c.gross)],['Government Deductions',peso(shares(view.c))],['Other Deductions',peso(view.c.deductions-shares(view.c))],['Net Pay',peso(view.c.net)],['Approval / Issuance Status','Unavailable']].map(([label,value])=><div key={label} className="flex justify-between gap-3"><dt>{label}</dt><dd className="m-0 font-semibold">{value}</dd></div>)}</dl><button className={`${ghost} mt-5`} onClick={()=>window.print()}>Print Preview</button></Modal>}
 </div>;
}
