import {useEffect,useState} from 'react';
import {Check,ClipboardList,Plus,RefreshCw,Save,ShieldCheck,Trash2,UserPlus,UserRound} from 'lucide-react';
import {Card,Empty,TextInput,button} from '../components/common/ui';
import {getCurrentUser} from '../features/auth/authService';
import {userService} from '../features/auth/userService';
import type {ManagedUser} from '../features/auth/userService';
import type {User} from '../types/domain';
import {read,write} from '../utils/storage';
import {readAuditEvents,recordAudit} from '../features/audit/auditService';

function fallbackUsers(current:User|null):ManagedUser[]{
 const stored=read<ManagedUser[]>('admin:users',[]);
 if(stored.length)return stored;
 return current?[{...current,email:'',status:'Active'}]:[];
}
const normalizedEvents=()=>readAuditEvents().map(event=>({...event,user:event.user||'Admin',module:event.module||'—',description:event.description||'—',ipDevice:event.ipDevice||'—'}));

export function UserAccountSettings(){
 const user=getCurrentUser();
 const[displayName,setDisplayName]=useState(()=>read<string>('admin:displayName',user?.name||'Admin'));
 const[saved,setSaved]=useState(false),[showAddUser,setShowAddUser]=useState(false),[users,setUsers]=useState<ManagedUser[]>(()=>fallbackUsers(user)),[loadingUsers,setLoadingUsers]=useState(true),[userError,setUserError]=useState('');
 const[newUser,setNewUser]=useState({name:'',employeeId:'',email:'',password:'',role:'HR Staff' as User['role']});
 useEffect(()=>{let mounted=true;userService.list().then(rows=>{if(mounted){setUsers(rows);setUserError(rows.some(row=>row.localOnly)?'User-management service is unavailable. Accounts can be added or deleted locally, but OTP sign-in requires the backend user function to be deployed.':'')}}).catch(()=>{if(mounted)setUserError('User service is unavailable. Existing local account information is shown. Please deploy the user-management functions before adding or deleting accounts.')}).finally(()=>{if(mounted)setLoadingUsers(false)});return()=>{mounted=false}},[]);
 const save=(event:React.FormEvent)=>{event.preventDefault();const nextName=displayName.trim()||'Admin';write('admin:displayName',nextName);recordAudit({action:'Updated profile',module:'Account Settings',description:`Changed administrator display name to ${nextName}.`});setSaved(true);window.setTimeout(()=>setSaved(false),2200)};
 const addUser=async(event:React.FormEvent)=>{event.preventDefault();const name=newUser.name.trim(),employeeId=newUser.employeeId.trim(),email=newUser.email.trim().toLowerCase();if(!name||!employeeId||!email||!newUser.password){setUserError('Name, employee ID, email, and password are required.');return}if(newUser.password.length<8){setUserError('Password must be at least 8 characters.');return}if(users.some(item=>item.employeeId.toLowerCase()===employeeId.toLowerCase())){setUserError('A user with this employee ID already exists.');return}if(users.some(item=>item.email&&item.email.toLowerCase()===email)){setUserError('A user with this email already exists.');return}try{const created=await userService.create({name,employeeId,email,password:newUser.password,role:newUser.role});setUsers(current=>[...current,created]);recordAudit({action:'Created user account',module:'Account Settings',description:`Created ${created.role} account for ${created.name} (${created.email}).${created.localOnly?' Backend OTP is pending deployment.':' An onboarding OTP was sent.'}`});setUserError(created.localOnly?'Account saved locally. OTP sign-in will work after the user-management backend is deployed.':'');setNewUser({name:'',employeeId:'',email:'',password:'',role:'HR Staff'});setShowAddUser(false)}catch(cause){setUserError(cause instanceof Error?cause.message:'The user account could not be created.')}};
 const deleteUser=async(account:ManagedUser)=>{if(account.id===user?.id){setUserError('You cannot delete your own account.');return}if(!window.confirm(`Delete the user account for ${account.name}? This cannot be undone.`))return;try{await userService.remove(account.id);setUsers(current=>current.filter(item=>item.id!==account.id));recordAudit({action:'Deleted user account',module:'Account Settings',description:`Deleted ${account.role} account for ${account.name} (${account.email}).`})}catch(cause){setUserError(cause instanceof Error?cause.message:'The user account could not be deleted.')}};
 return <div>
  <h1 className="m-0 text-[22px] font-semibold">User &amp; Account Settings</h1><p className="mt-1 max-w-[700px] text-[12.5px] text-[#6b7794]">Manage the signed-in administrator profile and user accounts.</p>
  <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.4fr)_minmax(260px,1fr)]"><Card><div className="mb-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><UserRound size={21}/></span><div><h2 className="m-0 text-[16px] font-semibold">Profile details</h2><p className="m-0 mt-1 text-[12px] text-slate-500">These details identify your administrator account.</p></div></div><form onSubmit={save} className="space-y-4"><label className="block text-[12px] font-semibold text-slate-600">Display name<div className="mt-1.5"><TextInput value={displayName} onChange={event=>setDisplayName(event.target.value)} aria-label="Display name"/></div></label><label className="block text-[12px] font-semibold text-slate-600">Employee ID<div className="mt-1.5"><TextInput value={user?.employeeId||'Unavailable'} readOnly aria-label="Employee ID" className="bg-slate-50"/></div></label><div className="flex items-center gap-3"><button type="submit" className={button}><Save size={15}/>Save changes</button>{saved&&<span role="status" className="inline-flex items-center gap-1 text-[12px] font-medium text-emerald-700"><Check size={15}/>Saved</span>}</div></form></Card><Card><div className="mb-4 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><ShieldCheck size={21}/></span><div><h2 className="m-0 text-[16px] font-semibold">Access</h2><p className="m-0 mt-1 text-[12px] text-slate-500">Current account permissions.</p></div></div><dl className="space-y-3 text-[13px]"><div className="flex justify-between gap-4"><dt className="text-slate-500">Name</dt><dd className="m-0 font-semibold text-slate-800">{user?.name||'Admin'}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Role</dt><dd className="m-0 font-semibold text-slate-800">{user?.role||'Admin'}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Session</dt><dd className="m-0 font-semibold text-emerald-700">Active</dd></div></dl></Card></div>
  <Card className="mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-50 text-violet-600"><UserPlus size={21}/></span><div><h2 className="m-0 text-[16px] font-semibold">User accounts</h2><p className="m-0 mt-1 text-[12px] text-slate-500">Create accounts with email/password credentials and send an onboarding OTP.</p></div></div><button type="button" className={button} onClick={()=>{setUserError('');setShowAddUser(value=>!value)}}><Plus size={15}/>{showAddUser?'Close':'Add user'}</button></div>
   {userError&&<p role="alert" className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-[12px] text-amber-800">{userError}</p>}
   {showAddUser&&<form onSubmit={addUser} className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="block text-[12px] font-semibold text-slate-600">Full name<div className="mt-1.5"><TextInput autoFocus value={newUser.name} onChange={event=>setNewUser({...newUser,name:event.target.value})} placeholder="e.g. Maria Santos"/></div></label><label className="block text-[12px] font-semibold text-slate-600">Employee ID<div className="mt-1.5"><TextInput value={newUser.employeeId} onChange={event=>setNewUser({...newUser,employeeId:event.target.value})} placeholder="e.g. EMP-002"/></div></label><label className="block text-[12px] font-semibold text-slate-600">Email<div className="mt-1.5"><TextInput type="email" value={newUser.email} onChange={event=>setNewUser({...newUser,email:event.target.value})} placeholder="user@company.com"/></div></label><label className="block text-[12px] font-semibold text-slate-600">Temporary password<div className="mt-1.5"><TextInput type="password" value={newUser.password} onChange={event=>setNewUser({...newUser,password:event.target.value})} placeholder="At least 8 characters"/></div></label></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="block text-[12px] font-semibold text-slate-600">Role<div className="mt-1.5"><select className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-[13px] outline-none focus:border-blue-500" value={newUser.role} onChange={event=>setNewUser({...newUser,role:event.target.value as User['role']})}><option value="HR Staff">HR Staff</option><option value="Admin">Admin</option></select></div></label><div className="flex items-end justify-end"><button type="submit" className={button}><UserPlus size={15}/>Create &amp; send OTP</button></div></div></form>}
   <div className="mt-5 overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[850px] text-left text-[13px]"><thead><tr className="border-b border-slate-200 bg-[#f7f9fc] text-[11px] uppercase tracking-wide text-slate-500"><th className="px-4 py-3">Name</th><th className="px-4 py-3">Employee ID</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{loadingUsers?<tr><td colSpan={6}><div role="status" className="py-8 text-center text-[13px] text-slate-500">Loading user accounts…</div></td></tr>:users.length===0?<tr><td colSpan={6}><Empty>No user accounts have been added yet.</Empty></td></tr>:users.map(item=><tr key={item.id} className="border-b border-slate-100 last:border-0"><td className="px-4 py-3 font-medium text-slate-800">{item.name}</td><td className="px-4 py-3 text-slate-500">{item.employeeId}</td><td className="px-4 py-3 text-slate-500">{item.email||'—'}</td><td className="px-4 py-3 text-slate-600">{item.role}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${item.localOnly?'bg-amber-50 text-amber-700':item.status==='Active'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{item.localOnly?'Local only':item.status}</span></td><td className="px-4 py-3"><button type="button" disabled={item.id===user?.id} title={item.id===user?.id?'You cannot delete your own account':'Delete user account'} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-[12px] font-semibold text-red-700 disabled:cursor-not-allowed disabled:opacity-40" onClick={()=>void deleteUser(item)}><Trash2 size={14}/>Delete</button></td></tr>)}</tbody></table></div>
  </Card>
 </div>;
}

export function LogsAudits(){
 const[events,setEvents]=useState(normalizedEvents);
 return <div><h1 className="m-0 text-[22px] font-semibold">Logs &amp; Audits</h1><p className="mt-1 max-w-[650px] text-[12.5px] text-[#6b7794]">Review recorded administrator activity and system audit events.</p><Card className="mt-5"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><ClipboardList size={21}/></span><div><h2 className="m-0 text-[16px] font-semibold">Audit activity</h2><p className="m-0 mt-1 text-[12px] text-slate-500">Events are shown in reverse chronological order.</p></div></div><button type="button" className={button} onClick={()=>setEvents(normalizedEvents())}><RefreshCw size={15}/>Refresh</button></div><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[980px] text-left text-[13px]"><thead><tr className="border-b border-slate-200 bg-[#f7f9fc] text-[11px] uppercase tracking-wide text-slate-500"><th scope="col" className="px-4 py-3">Date/time</th><th scope="col" className="px-4 py-3">User</th><th scope="col" className="px-4 py-3">Action</th><th scope="col" className="px-4 py-3">Module</th><th scope="col" className="px-4 py-3">Description</th><th scope="col" className="px-4 py-3">IP/device</th></tr></thead><tbody>{events.length===0?<tr><td colSpan={6}><Empty>No audit events have been recorded yet.</Empty></td></tr>:[...events].reverse().map(event=><tr key={event.id} className="border-b border-slate-100 last:border-0"><td className="whitespace-nowrap px-4 py-3 text-slate-500">{event.timestamp}</td><td className="px-4 py-3 font-medium text-slate-800">{event.user}</td><td className="px-4 py-3 font-medium text-slate-800">{event.action}</td><td className="px-4 py-3 text-slate-500">{event.module}</td><td className="min-w-[260px] px-4 py-3 text-slate-600">{event.description}</td><td className="whitespace-nowrap px-4 py-3 text-slate-500">{event.ipDevice}</td></tr>)}</tbody></table></div></Card></div>;
}
