import {useEffect,useState} from 'react';
import {FileText} from 'lucide-react';
import {Button,Card,Empty,ghost} from '../components/common/ui';
import type {Employee,PayrollInput} from '../types/domain';
import {employeeService} from '../features/employees/employeeService';
import {employeeName,normalizeClaims,saveClaims,statusClass} from '../features/claims/claimsTypes';
import type {ExpenseClaim,ClaimPaymentMethod} from '../features/claims/claimsTypes';
import {numberValue,peso,read,write} from '../utils/storage';
const today=()=>new Date().toISOString().slice(0,10);
export default function Reimbursement(){const[employees,setEmployees]=useState<Employee[]>([]);const[claims,setClaims]=useState<ExpenseClaim[]>([]);useEffect(()=>{employeeService.getAll().then(items=>{setEmployees(items);setClaims(normalizeClaims(items))})},[]);const update=(id:string,patch:Partial<ExpenseClaim>)=>setClaims(current=>{const next=current.map(item=>item.id===id?{...item,...patch,updatedAt:new Date().toISOString()}:item);saveClaims(next);return next});const payable=claims.filter(item=>(item.approvalStatus==='Approved'||item.approvalStatus==='Ready for Claim'||item.approvalStatus==='Sent to Finance')&&item.paymentStatus==='Unpaid');const paid=claims.filter(item=>item.paymentStatus!=='Unpaid');return <div><div><h1 className="m-0 text-[22px] font-semibold">Reimbursement</h1><p className="mt-1 max-w-[650px] text-[12.5px] text-[#6b7794]">Process payment for Finance-approved employee expense claims.</p></div><section className="mt-5"><h2 className="text-[15px] font-semibold">Finance-approved claims</h2><FinanceTable claims={payable} employees={employees} onPay={(claim,method)=>{const next=processPayment(claim,method,employees);if(next)update(claim.id,next)}}/></section><section className="mt-6"><h2 className="text-[15px] font-semibold">Reimbursement History</h2><HistoryTable claims={paid} employees={employees}/></section></div>}
function FinanceTable({claims,employees,onPay}:{claims:ExpenseClaim[];employees:Employee[];onPay:(claim:ExpenseClaim,method:ClaimPaymentMethod)=>void}){return <Card className="mt-3 overflow-x-auto"><table className="w-full min-w-[1150px] text-left text-[13px]"><thead><tr className="border-b border-[#e3e7ef] text-[11px] uppercase tracking-wide text-[#6b7794]">{['Claim Number','Claim Type / Purpose','Employee','Department','Amount','Approval Status','Receipt','Actions'].map(header=><th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody>{claims.length===0?<tr><td colSpan={8}><Empty>No Finance-approved claims are awaiting reimbursement.</Empty></td></tr>:claims.map(claim=><tr key={claim.id} className="border-b border-[#eef1f6]"><td className="px-4 py-3 font-semibold">{claim.claimNumber}</td><td className="px-4 py-3">{claim.claimType}<div className="max-w-[280px] text-[11px] text-[#6b7794]">{claim.businessPurpose}</div></td><td className="px-4 py-3">{employeeName(employees,claim.employeeId)}</td><td className="px-4 py-3">{claim.department||'—'}</td><td className="px-4 py-3 font-semibold">{peso(claim.amount)}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${statusClass(claim.approvalStatus)}`}>{claim.approvalStatus}</span></td><td className="px-4 py-3">{claim.receiptData?<button className="text-[#2f6b86] underline" onClick={()=>viewReceipt(claim)}>View receipt</button>:claim.receiptName||'Missing'}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-2"><Button onClick={()=>onPay(claim,'Paid Separately')}>Paid Separately</Button><button className={ghost} onClick={()=>onPay(claim,'Include in Payroll')}><FileText size={14}/>Include in Payroll</button></div></td></tr>)}</tbody></table></Card>}
function HistoryTable({claims,employees}:{claims:ExpenseClaim[];employees:Employee[]}){return <Card className="mt-3 overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-[13px]"><thead><tr className="border-b border-[#e3e7ef] text-[11px] uppercase tracking-wide text-[#6b7794]">{['Claim Number','Employee','Amount','Approval Status','Payment Status','Payment Date','Payment Method'].map(header=><th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody>{claims.length===0?<tr><td colSpan={7}><Empty>No reimbursement history yet.</Empty></td></tr>:claims.map(claim=><tr key={claim.id} className="border-b border-[#eef1f6]"><td className="px-4 py-3 font-semibold">{claim.claimNumber}</td><td className="px-4 py-3">{employeeName(employees,claim.employeeId)}</td><td className="px-4 py-3">{peso(claim.amount)}</td><td className="px-4 py-3">{claim.approvalStatus}</td><td className="px-4 py-3">{claim.paymentStatus}</td><td className="px-4 py-3">{claim.paymentDate||'—'}</td><td className="px-4 py-3">{claim.paymentMethod||'—'}</td></tr>)}</tbody></table></Card>}
function processPayment(claim:ExpenseClaim,method:ClaimPaymentMethod,employees:Employee[]):Partial<ExpenseClaim>|null{if(claim.paymentStatus!=='Unpaid')return null;if(method==='Include in Payroll'){const employee=employees.find(item=>item.id===claim.employeeId);const payroll=read<PayrollInput[]>('payroll:records',[]);const linked=read<Record<string,string[]>>('payroll:claim-links',{});if(!employee){alert('The employee could not be found.');return null}const index=payroll.findIndex(item=>item.empId===employee.employeeNo);if(index<0){alert('No applicable payroll record exists for this employee yet. Create the payroll record before including this claim.');return null}if(linked[claim.id]){alert('This claim has already been included in payroll.');return null}const row=payroll[index];payroll[index]={...row,otherEarnings:numberValue(row.otherEarnings)+claim.amount};write('payroll:records',payroll);linked[claim.id]=[String(row.id??index)];write('payroll:claim-links',linked);return{paymentStatus:'Included in Payroll',paymentMethod:method,paymentDate:today()};}return{paymentStatus:'Paid',paymentMethod:method,paymentDate:today()}}
function viewReceipt(claim:ExpenseClaim){if(!claim.receiptData){alert('Receipt data is not available for this claim.');return}const popup=window.open('','_blank','width=900,height=800');if(!popup)return;const safe=claim.receiptData.startsWith('data:application/pdf')?`<embed src="${claim.receiptData}" type="application/pdf" width="100%" height="90%"/>`:`<img src="${claim.receiptData}" alt="${claim.receiptName}" style="max-width:100%;max-height:90%;object-fit:contain"/>`;popup.document.write(`<title>${claim.receiptName}</title><body style="margin:20px;font-family:Arial"><h2>${claim.claimNumber} — ${claim.receiptName}</h2>${safe}</body>`);popup.document.close()}
