import {useEffect,useState} from 'react';
import {Check,FileText} from 'lucide-react';
import {Button,Card,Empty,ghost} from '../components/common/ui';
import type {Employee,PayrollInput} from '../types/domain';
import {employeeService} from '../features/employees/employeeService';
import {employeeName,normalizeClaims,saveClaims,statusClass} from '../features/claims/claimsTypes';
import type {ExpenseClaim,ClaimPaymentMethod} from '../features/claims/claimsTypes';
import {numberValue,peso,read,write} from '../utils/storage';
const today=()=>new Date().toISOString().slice(0,10);
export default function Reimbursement(){const[employees,setEmployees]=useState<Employee[]>([]);const[claims,setClaims]=useState<ExpenseClaim[]>([]);useEffect(()=>{employeeService.getAll().then(items=>{setEmployees(items);setClaims(normalizeClaims(items))})},[]);const update=(id:string,patch:Partial<ExpenseClaim>)=>setClaims(current=>{const next=current.map(item=>item.id===id?{...item,...patch,updatedAt:new Date().toISOString()}:item);saveClaims(next);return next});const ready=claims.filter(item=>item.approvalStatus==='Ready for Claim');const sent=claims.filter(item=>item.approvalStatus==='Sent to Finance');const paid=claims.filter(item=>item.paymentStatus!=='Unpaid');return <div><div><h1 className="m-0 text-[22px] font-semibold">Reimbursement</h1><p className="mt-1 max-w-[650px] text-[12.5px] text-[#6b7794]">Finance handoff and reimbursement processing for claims marked Ready for Claim.</p></div><Card className="mt-4 border-emerald-100 bg-emerald-50"><p className="m-0 text-[12px] text-emerald-800">Claims are only available here after review approval and the Ready for Claim status. Paid Separately does not change payroll; Include in Payroll adds the claim to the applicable payroll record.</p></Card><section className="mt-5"><h2 className="text-[15px] font-semibold">Ready for Finance</h2><ClaimTable claims={ready} employees={employees} action={(claim)=>update(claim.id,{approvalStatus:'Sent to Finance'})} actionLabel="Send to Finance"/></section><section className="mt-6"><h2 className="text-[15px] font-semibold">Sent to Finance</h2><FinanceTable claims={sent} employees={employees} onPay={(claim,method)=>{const next=processPayment(claim,method,employees);if(next)update(claim.id,next)}}/></section><section className="mt-6"><h2 className="text-[15px] font-semibold">Reimbursement History</h2><ClaimTable claims={paid} employees={employees} action={undefined} actionLabel=""/></section></div>}
function ClaimTable({claims,employees,action,actionLabel}:{claims:ExpenseClaim[];employees:Employee[];action?:((claim:ExpenseClaim)=>void);actionLabel:string}){return <Card className="mt-3 overflow-x-auto"><table className="w-full min-w-[950px] text-left text-[13px]"><thead><tr className="border-b border-[#e3e7ef] text-[11px] uppercase tracking-wide text-[#6b7794]">{['Claim Number','Employee','Amount','Approval Status','Payment Status','Payment Date','Receipt','Action'].map(header=><th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody>{claims.length===0?<tr><td colSpan={8}><Empty>No claims in this queue.</Empty></td></tr>:claims.map(claim=><tr key={claim.id} className="border-b border-[#eef1f6]"><td className="px-4 py-3 font-semibold">{claim.claimNumber}</td><td className="px-4 py-3">{employeeName(employees,claim.employeeId)}<div className="text-[11px] text-[#6b7794]">{claim.department}</div></td><td className="px-4 py-3 font-semibold">{peso(claim.amount)}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${statusClass(claim.approvalStatus)}`}>{claim.approvalStatus}</span></td><td className="px-4 py-3">{claim.paymentStatus}</td><td className="px-4 py-3">{claim.paymentDate||'—'}</td><td className="px-4 py-3">{claim.receiptData?<button className="text-[#2f6b86] underline" onClick={()=>viewReceipt(claim)}>View receipt</button>:claim.receiptName||'Missing'}</td><td className="px-4 py-3">{action&&claim.paymentStatus==='Unpaid'?<Button onClick={()=>action(claim)}><Check size={14}/>{actionLabel}</Button>:<span className="text-[12px] text-[#6b7794]">—</span>}</td></tr>)}</tbody></table></Card>}
function FinanceTable({claims,employees,onPay}:{claims:ExpenseClaim[];employees:Employee[];onPay:(claim:ExpenseClaim,method:ClaimPaymentMethod)=>void}){return <Card className="mt-3 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-[13px]"><thead><tr className="border-b border-[#e3e7ef] text-[11px] uppercase tracking-wide text-[#6b7794]">{['Claim Number','Claim Type / Purpose','Employee','Amount','Payment Status','Payment Method','Receipt','Actions'].map(header=><th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody>{claims.length===0?<tr><td colSpan={8}><Empty>No claims have been sent to Finance.</Empty></td></tr>:claims.map(claim=><tr key={claim.id} className="border-b border-[#eef1f6]"><td className="px-4 py-3 font-semibold">{claim.claimNumber}</td><td className="px-4 py-3">{claim.claimType}<div className="max-w-[260px] text-[11px] text-[#6b7794]">{claim.businessPurpose}</div></td><td className="px-4 py-3">{employeeName(employees,claim.employeeId)}</td><td className="px-4 py-3 font-semibold">{peso(claim.amount)}</td><td className="px-4 py-3">{claim.paymentStatus}</td><td className="px-4 py-3">{claim.paymentMethod||'—'}</td><td className="px-4 py-3">{claim.receiptData?<button className="text-[#2f6b86] underline" onClick={()=>viewReceipt(claim)}>View receipt</button>:claim.receiptName||'Missing'}</td><td className="px-4 py-3">{claim.paymentStatus==='Unpaid'?<div className="flex flex-wrap gap-2"><Button onClick={()=>onPay(claim,'Paid Separately')}>Paid Separately</Button><button className={ghost} onClick={()=>onPay(claim,'Include in Payroll')}><FileText size={14}/>Include in Payroll</button></div>:<span className="text-[12px] text-[#6b7794]">Processed</span>}</td></tr>)}</tbody></table></Card>}
function processPayment(claim:ExpenseClaim,method:ClaimPaymentMethod,employees:Employee[]):Partial<ExpenseClaim>|null{if(claim.paymentStatus!=='Unpaid')return null;if(method==='Include in Payroll'){const employee=employees.find(item=>item.id===claim.employeeId);const payroll=read<PayrollInput[]>('payroll:records',[]);const linked=read<Record<string,string[]>>('payroll:claim-links',{});if(!employee){alert('The employee could not be found.');return null}const index=payroll.findIndex(item=>item.empId===employee.employeeNo);if(index<0){alert('No applicable payroll record exists for this employee yet. Create the payroll record before including this claim.');return null}if(linked[claim.id]){alert('This claim has already been included in payroll.');return null}const row=payroll[index];payroll[index]={...row,otherEarnings:numberValue(row.otherEarnings)+claim.amount};write('payroll:records',payroll);linked[claim.id]=[String(row.id??index)];write('payroll:claim-links',linked);return{paymentStatus:'Included in Payroll',paymentMethod:method,paymentDate:today()};}return{paymentStatus:'Paid',paymentMethod:method,paymentDate:today()}}

function viewReceipt(claim:ExpenseClaim){if(!claim.receiptData){alert('Receipt data is not available for this claim.');return}const popup=window.open('','_blank','width=900,height=800');if(!popup)return;const safe=claim.receiptData.startsWith('data:application/pdf')?`<embed src=\"${claim.receiptData}\" type=\"application/pdf\" width=\"100%\" height=\"90%\"/>`:`<img src=\"${claim.receiptData}\" alt=\"${claim.receiptName}\" style=\"max-width:100%;max-height:90%;object-fit:contain\"/>`;popup.document.write(`<title>${claim.receiptName}</title><body style=\"margin:20px;font-family:Arial\"><h2>${claim.claimNumber} — ${claim.receiptName}</h2>${safe}</body>`);popup.document.close()}
