import {useEffect,useRef} from 'react';
import type {ButtonHTMLAttributes,InputHTMLAttributes,ReactNode,RefObject} from 'react';
import {Inbox,X} from 'lucide-react';
export const input='pbms-input w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-[13px] outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 disabled:bg-slate-50 disabled:text-slate-400';
export const button='pbms-button inline-flex items-center justify-center gap-2 rounded-xl bg-[#17345b] px-4 py-2.5 text-[13px] font-semibold text-white shadow-sm transition hover:bg-[#224a7c] disabled:cursor-not-allowed disabled:opacity-50';
export const ghost='pbms-secondary inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-[13px] font-semibold text-slate-600 transition hover:border-slate-300 hover:bg-slate-50 hover:text-slate-900 disabled:cursor-not-allowed disabled:opacity-50';
export function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-[12px] font-semibold text-slate-600">{label}<div className="mt-1.5">{children}</div></label>}
export function TextInput({className='',...props}:InputHTMLAttributes<HTMLInputElement>){return <input className={`${input} ${className}`} {...props}/>}
export function Button({className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className={`${button} ${className}`} {...props}/>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <div className={`pbms-card rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_2px_8px_rgba(15,23,42,0.025)] ${className}`}>{children}</div>}
export function Empty({children='No records yet.'}:{children?:ReactNode}){return <div className="pbms-empty flex flex-col items-center justify-center gap-3 rounded-xl px-4 py-12 text-center text-[13px] leading-relaxed text-slate-500"><span aria-hidden="true" className="grid h-12 w-12 place-items-center rounded-2xl border border-slate-200 bg-slate-50 text-slate-400"><Inbox size={23} strokeWidth={1.5}/></span><div className="max-w-lg">{children}</div></div>}
export function useOverlayFocus(ref:RefObject<HTMLDivElement>,open:boolean,onClose:()=>void){
 const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{if(!open||!ref.current)return;const panel=ref.current;const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';
 const controls=()=>Array.from(panel.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')).filter(item=>item.getClientRects().length>0);
 (controls()[0]??panel).focus();
 const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();close.current();return}if(event.key==='Tab'){const items=controls();const first=items[0],last=items[items.length-1];if(!first){event.preventDefault();panel.focus()}else if(event.shiftKey&&(document.activeElement===first||!panel.contains(document.activeElement))){event.preventDefault();last.focus()}else if(!event.shiftKey&&(document.activeElement===last||!panel.contains(document.activeElement))){event.preventDefault();first.focus()}}};
 document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus()};
 },[open,ref]);
}
export function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:ReactNode;wide?:boolean}){const panel=useRef<HTMLDivElement>(null);useOverlayFocus(panel,true,onClose);return <div className="pbms-modal fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm" onClick={onClose}><div ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={`max-h-[90vh] w-full overflow-y-auto rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl ${wide?'max-w-2xl':'max-w-md'}`} onClick={e=>e.stopPropagation()}><div className="mb-6 flex items-center justify-between gap-4 border-b border-slate-100 pb-4"><h3 className="m-0 text-[18px] font-semibold tracking-tight text-slate-900">{title}</h3><button type="button" onClick={onClose} aria-label="Close" className="grid h-8 w-8 shrink-0 place-items-center rounded-lg text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"><X size={18}/></button></div>{children}</div></div>}
