import type {Employee} from '../../types/domain';
import {read,write} from '../../utils/storage';

export type ClaimApprovalStatus='Pending Approval'|'Approved'|'Rejected'|'Returned';
export type ClaimPaymentStatus='Unpaid'|'Included in Payroll'|'Paid';
export type ClaimPaymentMethod='Paid Separately'|'Include in Payroll'|'';
export type ClaimType='Food'|'Transportation'|'Office Supplies';
export const claimTypes:ClaimType[]=['Food','Transportation','Office Supplies'];
export interface ExpenseClaim{id:string;claimNumber:string;claimType:ClaimType;employeeId:string;department:string;amount:number;date:string;businessPurpose:string;projectSite:string;receiptName:string;receiptData?:string;certified:boolean;approvalStatus:ClaimApprovalStatus;paymentStatus:ClaimPaymentStatus;paymentMethod:ClaimPaymentMethod;paymentDate:string;createdAt:string;updatedAt:string;notes:string}
export interface LegacyClaim{[key:string]:unknown}

const demoClaims:ExpenseClaim[]=[
  {id:'demo-claim-pending-2026-0001',claimNumber:'CLM-2026-0001',claimType:'Office Supplies',employeeId:'demo-employee-juan-dela-cruz',department:'Operations',amount:1250,date:'2026-10-03',businessPurpose:'Purchase of office supplies required for the Operations team.',projectSite:'',receiptName:'juan-office-supplies-receipt.pdf',receiptData:undefined,certified:true,approvalStatus:'Pending Approval',paymentStatus:'Unpaid',paymentMethod:'',paymentDate:'',createdAt:'2026-10-03T09:00:00.000Z',updatedAt:'2026-10-03T09:00:00.000Z',notes:''},
  {id:'demo-claim-approved-2026-0002',claimNumber:'CLM-2026-0002',claimType:'Transportation',employeeId:'demo-employee-maria-santos',department:'Human Resources',amount:850,date:'2026-09-28',businessPurpose:'Business transportation incurred for an approved Human Resources activity.',projectSite:'',receiptName:'maria-transportation-receipt.pdf',receiptData:undefined,certified:true,approvalStatus:'Approved',paymentStatus:'Unpaid',paymentMethod:'',paymentDate:'',createdAt:'2026-09-28T09:00:00.000Z',updatedAt:'2026-09-28T09:00:00.000Z',notes:''},
  {id:'demo-claim-returned-2026-0003',claimNumber:'CLM-2026-0003',claimType:'Food',employeeId:'demo-employee-ana-reyes',department:'Administration',amount:1500,date:'2026-10-05',businessPurpose:'Meals provided during a company business meeting.',projectSite:'',receiptName:'ana-business-meeting-meals-receipt.pdf',receiptData:undefined,certified:true,approvalStatus:'Returned',paymentStatus:'Unpaid',paymentMethod:'',paymentDate:'',createdAt:'2026-10-05T09:00:00.000Z',updatedAt:'2026-10-05T09:00:00.000Z',notes:'Returned for correction or additional documentation.'},
  {id:'demo-claim-approved-2026-0004',claimNumber:'CLM-2026-0004',claimType:'Food',employeeId:'demo-employee-carlo-mendoza',department:'Sales',amount:2350,date:'2026-10-06',businessPurpose:'Meals provided during a client-related business meeting.',projectSite:'',receiptName:'carlo-client-meeting-meals-receipt.pdf',receiptData:undefined,certified:true,approvalStatus:'Approved',paymentStatus:'Unpaid',paymentMethod:'',paymentDate:'',createdAt:'2026-10-06T09:00:00.000Z',updatedAt:'2026-10-06T09:00:00.000Z',notes:''}
];
const approval=(value:unknown):ClaimApprovalStatus=>{if(value==='Submitted'||value==='Pending Approval'||value==='Pending Finance Approval')return 'Pending Approval';if(value==='Approved'||value==='Ready for Claim'||value==='Sent to Finance')return 'Approved';if(value==='Rejected'||value==='Returned')return value;return 'Pending Approval'};
const payment=(value:unknown):ClaimPaymentStatus=>value==='Paid'?'Paid':value==='Included in Payroll'?'Included in Payroll':'Unpaid';
function normalizeRow(row:LegacyClaim,index:number,employees:Employee[]):ExpenseClaim{const employee=employees.find(item=>item.id===String(row.employeeId??''));const rawType=String(row.claimType??row.category??'Office Supplies');const mappedType=rawType==='Meals'?'Food':rawType;const claimType=(claimTypes.includes(mappedType as ClaimType)?mappedType:'Office Supplies') as ClaimType;return{id:String(row.id??crypto.randomUUID()),claimNumber:String(row.claimNumber??`CLM-${String(index+1).padStart(4,'0')}`),claimType,employeeId:String(row.employeeId??''),department:String(row.department??employee?.department??''),amount:Number(row.amount??0),date:String(row.date??String(row.createdAt??'').slice(0,10)),businessPurpose:String(row.businessPurpose??''),projectSite:String(row.projectSite??''),receiptName:String(row.receiptName??''),receiptData:row.receiptData?String(row.receiptData):undefined,certified:Boolean(row.certified),approvalStatus:approval(row.approvalStatus??row.status),paymentStatus:payment(row.paymentStatus),paymentMethod:(row.paymentMethod==='Paid Separately'||row.paymentMethod==='Include in Payroll'?row.paymentMethod:''),paymentDate:String(row.paymentDate??''),createdAt:String(row.createdAt??new Date().toISOString()),updatedAt:String(row.updatedAt??row.createdAt??new Date().toISOString()),notes:String(row.notes??'')}}
export function normalizeClaims(employees:Employee[]):ExpenseClaim[]{const rows=read<LegacyClaim[]>('claims:records',[]);const existing=rows.map((row,index)=>normalizeRow(row,index,employees));const byNumber=new Map(existing.map(item=>[item.claimNumber,item]));const seedVersion=read<number>('claims:demo-seed-version',read<boolean>('claims:demo-seeded',false)?3:0);if(seedVersion<4){demoClaims.forEach(sample=>{if(!byNumber.has(sample.claimNumber))byNumber.set(sample.claimNumber,sample)});const merged=[...byNumber.values()];saveClaims(merged);write('claims:demo-seeded',true);write('claims:demo-seed-version',4);return merged}return [...byNumber.values()]}
export function saveClaims(claims:ExpenseClaim[]){write('claims:records',claims)}
export function nextClaimNumber(items:ExpenseClaim[]){const highest=items.reduce((max,item)=>{const match=/^CLM-(?:2026-)?(\d+)$/i.exec(item.claimNumber);return match?Math.max(max,Number(match[1])):max},0);return `CLM-2026-${String(highest+1).padStart(4,'0')}`}
export function employeeName(employees:Employee[],id:string){const employee=employees.find(item=>item.id===id);if(employee)return `${employee.name} (${employee.employeeNo})`;const demoNames:Record<string,string>={'demo-employee-juan-dela-cruz':'Juan Dela Cruz','demo-employee-maria-santos':'Maria Santos','demo-employee-ana-reyes':'Ana Reyes','demo-employee-carlo-mendoza':'Carlo Mendoza'};return demoNames[id]??id}
export function statusClass(status:string){return status==='Approved'||status==='Ready for Claim'||status==='Sent to Finance'||status==='Paid'||status==='Included in Payroll'?'bg-emerald-50 text-emerald-700':status==='Rejected'?'bg-red-50 text-red-700':status==='Returned'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-700'}
