import type {Employee} from '../../types/domain';
import {read,write} from '../../utils/storage';

export type ClaimApprovalStatus='Pending Approval'|'Approved'|'Ready for Claim'|'Sent to Finance'|'Rejected'|'Returned';
export type ClaimPaymentStatus='Unpaid'|'Included in Payroll'|'Paid';
export type ClaimPaymentMethod='Paid Separately'|'Include in Payroll'|'';
export type ClaimType='Food'|'Transportation'|'Office Supplies';
export const claimTypes:ClaimType[]=['Food','Transportation','Office Supplies'];
export interface ExpenseClaim{id:string;claimNumber:string;claimType:ClaimType;employeeId:string;department:string;amount:number;date:string;businessPurpose:string;projectSite:string;receiptName:string;receiptData?:string;certified:boolean;approvalStatus:ClaimApprovalStatus;paymentStatus:ClaimPaymentStatus;paymentMethod:ClaimPaymentMethod;paymentDate:string;createdAt:string;updatedAt:string;notes:string}
export interface LegacyClaim{[key:string]:unknown}
const approval=(value:unknown):ClaimApprovalStatus=>{if(value==='Submitted')return 'Pending Approval';if(value==='Approved'||value==='Ready for Claim'||value==='Sent to Finance'||value==='Rejected'||value==='Returned')return value;return 'Pending Approval'};
const payment=(value:unknown):ClaimPaymentStatus=>value==='Paid'||value==='Included in Payroll'?'Included in Payroll'===value?'Included in Payroll':'Paid':'Unpaid';
export function normalizeClaims(employees:Employee[]):ExpenseClaim[]{const rows=read<LegacyClaim[]>('claims:records',[]);return rows.map((row,index)=>{const employee=employees.find(item=>item.id===String(row.employeeId??''));const rawType=String(row.claimType??row.category??'Other');const claimType=(claimTypes.includes(rawType as ClaimType)?rawType:'Office Supplies') as ClaimType;const rawStatus=approval(row.approvalStatus??row.status);const rawPayment=payment(row.paymentStatus);const status=rawPayment!=='Unpaid'&&rawStatus==='Approved'?'Sent to Finance':rawStatus;return{id:String(row.id??crypto.randomUUID()),claimNumber:String(row.claimNumber??`CLM-${String(index+1).padStart(4,'0')}`),claimType,employeeId:String(row.employeeId??''),department:String(row.department??employee?.department??''),amount:Number(row.amount??0),date:String(row.date??String(row.createdAt??'').slice(0,10)),businessPurpose:String(row.businessPurpose??''),projectSite:String(row.projectSite??''),receiptName:String(row.receiptName??''),receiptData:row.receiptData?String(row.receiptData):undefined,certified:Boolean(row.certified),approvalStatus:status,paymentStatus:rawPayment,paymentMethod:(row.paymentMethod==='Paid Separately'||row.paymentMethod==='Include in Payroll'?row.paymentMethod:''),paymentDate:String(row.paymentDate??''),createdAt:String(row.createdAt??new Date().toISOString()),updatedAt:String(row.updatedAt??row.createdAt??new Date().toISOString()),notes:String(row.notes??'')}})}
export function saveClaims(claims:ExpenseClaim[]){write('claims:records',claims)}
export function nextClaimNumber(items:ExpenseClaim[]){const highest=items.reduce((max,item)=>{const match=/^CLM-(\d+)$/i.exec(item.claimNumber);return match?Math.max(max,Number(match[1])):max},0);return `CLM-${String(highest+1).padStart(4,'0')}`}
export function employeeName(employees:Employee[],id:string){const employee=employees.find(item=>item.id===id);return employee?`${employee.name} (${employee.employeeNo})`:id}
export function statusClass(status:string){return status==='Approved'||status==='Ready for Claim'||status==='Sent to Finance'||status==='Paid'||status==='Included in Payroll'?'bg-emerald-50 text-emerald-700':status==='Rejected'?'bg-red-50 text-red-700':status==='Returned'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-700'}
